### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by Otumian-empire** [Otumian-empire/todo-app-cli#1]
# Document how to do the following local server:
- clone app
- create database
- install modules
- run app
- run tests
> I am available and open for discussion

**Comment by sawyer1997** [comment]
Hi @Otumian-empire , wanted to give a shot.

**Comment by Otumian-empire** [comment]
okay.. @sawyer1997 .. let me know if you need any information..

**Comment by sawyer1997** [comment]
@Otumian-empire please assign this issue to me, have already started working.
